name: sample_dart_project
description: A sample Dart project with vulnerabilities.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  sqlite3: ^1.0.1
