name: Example workflow for Dart using Snyk

on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: dart pub get

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: 🔍 Run Semgrep for SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: run Snyk Code Test
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
